
name: "debug-plm"
steps: 1000
probe_freq: 100
seed: 777
optim:
    lr: 3e-4
    warmup: 2000
    lr_min_ratio: 0.000001
    clip: 10.0

distributed:
    fsdp_type: full_shard
    compile: true
    model_dtype: bf16
    matmul_allow_tf32: false
    selective_activation_checkpointing: false
    tp_size: 1

model:
    dim: 1024
    n_layers: 8
    n_heads: 8
    vocab_size: 24

data:
    root_dir: /lus/eagle/projects/FoundEpidem/hippekp/genslm-foundation/data/ncbi/refseq.parsed/faa-jsonl
    sources:
        refseq: 1.0
    batch_size: 32
    prefetch_size: 64
    seq_len: 2048
    n_views: 2
    load_async: true
    add_bos: true
    add_eos: true
    tokenizer:
        name: aa

profiling:
    run: true

checkpoint:
    dump:
        every: 100
        keep: 1
    eval:
        every: 100
        keep: 1

logging:
    freq: 10
